# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
 - package-ecosystem: "npm"
   directory: "/" # Location of package.json
   schedule:
    interval: "weekly" # Options: "daily", "weekly", "monthly"
   commit-message:
    prefix: "update" # Prefix for the commit message
   open-pull-requests-limit: 5 # Limit the number of open PRs
   target-branch: "dev"

 - package-ecosystem: "cargo"
   directory: "/" # Location of Cargo.toml
   schedule:
    interval: "weekly" # Options: "daily", "weekly", "monthly"
   commit-message:
    prefix: "update" # Prefix for the commit message
   open-pull-requests-limit: 5 # Limit the number of open PRs
   target-branch: "dev"
