name: lx
services:
  worker:
    build:
      dockerfile: Infrastructure/Worker.dockerfile
      target: ${WORKER_TARGET_STAGE}
      context: ../..
    tty: true
    ports:
      - "1337:1337"
    volumes:
      - ../..:/workspace
      - lx-cmake-build:/build
  frontend:
    build:
      dockerfile: Dockerfile
      target: ${FRONTEND_TARGET_STAGE}
      context: ../../Sources/lxui
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ../../:/workspace

volumes:
  lx-cmake-build:


networks:
  default:
    name: "lx"
