name: lx
services:
  worker:
    build:
      dockerfile: Infrastructure/Worker.dockerfile
      target: ${WORKER_TARGET_STAGE}
      context: ../..
    tty: true
    ports:
      - "1337:1337"
    volumes:
      - ../..:/workspace
  frontend:
    build:
      dockerfile: Infrastructure/WebFrontend.dockerfile
      target: ${FRONTEND_TARGET_STAGE}
      context: ../..
    tty: true
    ports:
      - "4434:8080"
    volumes:
      - ../../:/workspace
    environment:
      - BACKEND_HOST=worker.local
      - BACKEND_PORT=1337
networks:
  default:
    name: "lx"
