name: lx
services:
  worker:
    build:
      context: ../..
      dockerfile: Infrastructure/Worker.dockerfile
      target: ${WORKER_TARGET_STAGE}
      args:
        - BUILD_MODE=debug-local
    tty: true
    ports:
      - "1337:1337"
    volumes:
      - ../..:/workspace
  frontend:
    build:
      context: ../..
      dockerfile: Infrastructure/WebFrontend.dockerfile
      target: ${FRONTEND_TARGET_STAGE}
      args:
        - BUILD_MODE=debug-local
    tty: true
    ports:
      - "4434:8080"
    volumes:
      - ../../:/workspace
  web-server:
    build:
      context: ../..
      dockerfile: Sources/WebServer/Dockerfile
      target: ${WEB_SERVER_TARGET_STAGE}
      args:
        - BUILD_MODE=debug-local
    tty: true
    ports:
      - "4433:4433"
networks:
  default:
    name: "traefik_proxy_sprachguru_prod_local"
