spring:
  rabbitmq:
    host: rabbitmq-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak-server:8080/auth/realms/LAND_OOE_SPRACHGURU/protocol/openid-connect/certs
        policy-enforcer-config: #/policy-enforcer.json
          auth-server-url: http://keycloak-server:8080/auth
          credentials:
            secret: ENC(Yqs+VMpphc6AWlygrjoKCPpr6g8SS8ThrXZUpnmzEHyOL8A/pCDlBNM0AljK7vmZfB3lMAUBWlG995ymydwOFD7DUZF+Fih16tTLNa1D0ng=)
        cors-config: https://innovation-studio.landooe.fivesquare.dev, https://lx.landooe.fivesquare.dev, http://localhost:4434