server:
  port: 8420
  servlet:
    context-path: /central-server/
hal:
  uri:
    task: http://localhost:8050/db-service/tasks
    page-size: 10
    sort-criteria: id
spring:
  rabbitmq:
    port: 5672
    host: localhost
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:4020/auth/realms/LAND_OOE_SPRACHGURU/protocol/openid-connect/certs
        policy-enforcer-config: #/policy-enforcer.json
          realm: LAND_OOE_SPRACHGURU
          auth-server-url: http://localhost:4020/auth
          resource: central-server
          credentials:
            secret: ENC(NKy6SuyyttfWT7RqLcST9aTNOBjv3j2mb2zCFM/WpVpS58zizssCgAUev1rtQb+QJBWmVkEkzj/pyAtK0PrhBmPf69ee0lZJosVbgjPvrDQ=)
        cors-config: http://localhost:4200
audio:
  conversion:
    ffmpeg_path: /usr/bin/ #C:/Program Files/ffmpeg/ffmpeg-6.1-full_build/bin
    accepted_formats: audio/x-m4a, audio/vnd.dlna.adts
    dss_conversion_url: http://localhost:5000/api/AudioConvert/upload?returnUrl=blub
minio:
  endpoint: http://localhost:9000
  username: m1n10-usr
  password: ENC(7QHogW9K6/07iBVr4MXSGIaRTG/wKkwdKT3OWSGUz/mlQpqIMRhXfWZVfhdQFAvsNxgPsh/AS5FRrM9DwlxDpQ==)
  buckets: audio-raw, audio-converted, video-raw, video-converted, document-raw, document-converted
celery:
  task:
    init:
      listener: true
      registry: true
    reply_to: responseQueue
    content_encoding: utf-8
    content_type: application/json
    file:
      accepted_types:
        video: mp4,mov,m4v,3gp
        audio: wav,aac,mp3,m4a
        text: pdf,docx,doc,txt
    properties:
      lang: py
    transcription:
      header:
        task:
          name: task
          value: sprachguru_audio_workers.transcribe_audio
        task_id:
          name: id
    translation:
      header:
        task:
          audio:
            value: sprachguru_audio_workers.translate_audio
          text:
            value: sprachguru_language_workers.translate_text
          file:
            value: sprachguru_language_workers.translate_file
    test:
      header:
        task:
          value: tasks_app.workers.test_tasks.test_states
    queue:
      transcription: transcription
      translation:
        audio: translation
        file: fileTranslation
        text: textTranslation
      dictation: dictation
