hal:
  uri:
    task: http://db-service:8050/db-service/tasks
spring:
  rabbitmq:
    host: rabbitmq-server
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak-server:8080/auth/realms/LAND_OOE_SPRACHGURU/protocol/openid-connect/certs
        policy-enforcer-config: #/policy-enforcer.json
          auth-server-url: http://keycloak-server:8080/auth
          credentials:
            secret: ENC(mh7on4X2+2e41aJSN8vBWQ+TGYinHIrj10Y7GdUpPLfGPMWqQ4bSK7Y2gGyUpwXw7su22ocKapkHFaQrcwTihnme1kbWX//0LJKjg+/XFm4=)
        cors-config: http://localhost:4200,http:localhost:4020
minio:
  endpoint: http://minio-server:9000
