name: lx
services:
  worker:
    build:
      dockerfile: Infrastructure/Worker.dockerfile
      target: dev
      context: ..
    tty: true
    volumes:
      - ..:/workspace
  rabbitmq-server:
    user: "1000:1000"
    cap_drop:
      - ALL
    security_opt:
      - "no-new-privileges=true"
    image: rabbitmq:3-management-alpine
  prototype-pipeline-basic-auth:
    user: "1000:1000"
    cap_drop:
      - ALL
    security_opt:
      - "no-new-privileges=true"
    ports:
      - "8433:8433"
    image: containers.github.scch.at/land-ooe/prototype-pipeline:4.0.2-SNAPSHOT-local-basic-auth-dev
    restart: always
    depends_on:
      - rabbitmq-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prototype-pipeline-basic-auth.rule=Host(`localhost`) && PathPrefix(`/lx`)"
      - "traefik.http.routers.prototype-pipeline-basic-auth.entrypoints=web"
      - "traefik.http.services.prototype-pipeline-basic-auth.loadbalancer.server.port=8433"

networks:
  default:
    name: "lx"
