name: Docker Image CI

on:
  push:
    branches: [ "main", "stable" ]
  pull_request:
    branches: [ "main", "stable" ]

jobs:

  build:

    runs-on: [ self-hosted ]

    steps:
    - uses: actions/checkout@v4
    - name: Build the Worker image
      run: docker build . --file Infrastructure/Worker.dockerfile --tag lxui-worker:$(date +%s)
    - name: Build the Frontend image
      run: docker build . --file Sources/lxui/Dockerfile --tag lxui-frontend:$(date +%s)
