name: Build Docker Image 🐋
on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0 13 * * 1"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/lx-worker

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Extract branch name
        shell: bash
        run: |
          branch="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          branch="${branch//\//_}"
          echo "branch=$branch" >> $GITHUB_OUTPUT
        id: fetch_branch

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Delete previous builds
        uses: actions/delete-package-versions@v5
        continue-on-error: true
        with:
          package-name: lx-worker
          package-type: container
          min-versions-to-keep: 10

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,suffix=-{{date 'YYYYMMDD'}}
            type=ref,event=tag,suffix=-{{date 'YYYYMMDD'}}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          file: Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.fetch_branch.outputs.branch }}-latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_VARIANT=release
