name: Docker Image CI

on:
  push:
    branches: [ "main", "stable", "dev" ]
  pull_request:
    branches: [ "main", "stable", "dev" ]

jobs:
  build:
    runs-on: [ KRAKAU ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to github container registry
      uses: docker/login-action@v2
      with:
        registry: containers.github.scch.at
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Extract metadata (tags, labels) for Docker
      id: frontend-meta
      uses: docker/metadata-action@v4
      with:
        images:  containers.github.scch.at/Land-OOE/prolog-landesabgabe-frontend
        tags: |
            type=ref,event=branch,suffix=-{{ date -s }}
            type=ref,event=tag,suffix=-{{ date -s }}
    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        push: true
        file: ./Sources/lxui/Dockerfile
        context: ./Sources/lxui/
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ steps.frontend-meta.outputs.tags }}
        labels: ${{ steps.frontend-meta.outputs.labels }}
    - name: Extract metadata (tags, labels) for Docker
      id: backend-meta
      uses: docker/metadata-action@v4
      with:
        images:  containers.github.scch.at/Land-OOE/prolog-landesabgabe-backend
        tags: |
            type=ref,event=branch,suffix=-{{ date -s }}
            type=ref,event=tag,suffix=-{{ date -s }}
    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        push: true
        file: ./Infrastructure/Worker.dockerfile
        context: .
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ steps.backend-meta.outputs.tags }}
        labels: ${{ steps.backend-meta.outputs.labels }}
